export const TRIGGER_USER_DETAILS = "TRIGGER_USER_DETAILS";
export const TRIGGER_LEAD_DETAILS = "TRIGGER_LEAD_DETAILS";
export const TRIGGER_REVIEW_APPLICATION_DETAILS =
  "TRIGGER_REVIEW_APPLICATION_DETAILS";
